### ISSUE TITLE
QuoteExceededError from localStorage

### ISSUE THREAD

**Issue by luke-atp** [authts/oidc-client-ts#466] opened 2022-04-05 16:49 UTC
I am receiving errors from the oidc-client-ts library when storing data in localStorage. I also notice many values in localStorage over time, all with different keys.

My configuration user manager settings are:

```javascript
{
      authority: '',
      client_id: '',
      redirect_uri: ``,
      scope: 'openid, profile ...',
      response_type: 'code',
      post_logout_redirect_uri: '',
      filterProtocolClaims: false,
      automaticSilentRenew: true,
      silent_redirect_uri: ''
}
```

Is there some configuration that I am missing that is not cleaning up the old values?

Below is a screenshot of the error.

![image (2)](https://user-images.githubusercontent.com/72394976/161804782-b9540ed5-7491-45d0-9c41-fd4a47009973.png)

**Comment by pamapa** [comment] 2022-04-06 11:25
I guess you local storage exceeds the max. size of 10 MB. As local storage is shared between applications, it is probably caused by other applications, maybe a clean helps...

**Comment by luke-atp** [comment] 2022-04-06 12:51
Cleaning localStorage does resolve the issue temporarily. However, it appears to be oidc-client data that is filling up the space.

Over time the records below continue to be added, and never removed from localStorage.

![oidc-client-ts-localStorage](https://user-images.githubusercontent.com/72394976/161978540-ccb0e330-b96c-44e9-b915-9ed6055b30cb.png)

**Comment by pamapa** [comment] 2022-04-06 13:56
Ups, that should not happen, can you debug (or enable Console logging) why that happens, on my side i have not seen that yet....

**Comment by luke-atp** [comment] 2022-04-06 14:02
Yeah, I can enable DEBUG and log out everything that is happening. I'm not seeing any errors. Is there anything in particular that would be helpful?

**Comment by kherock** [comment] 2022-04-06 16:29
I also see this, but it's never when I'm looking. Though I do know that this will happen under certain circumstances when a sign in request fails. For example, the sign-in attempt fails at the IDP, and the window never returns to the website to be cleaned up.

**Comment by kherock** [comment] 2022-04-06 16:53
@pamapa currently this library never runs `.clearStaleState()` in any automatic fashion. I don't think we have a leak to patch here, I think it's just a problem of incomplete authorization requests piling up while developing a new application. How do you feel about automatically running it at the beginning of `OidcClient#createSigninRequest()`?

**Comment by luke-atp** [comment] 2022-04-06 20:51
After some time, I was finally able to find more records getting added to localStorage. @kherock may be on the right track. I got the errors when I killed my angular application. However, I wonder if it is also happening when my computer goes to sleep.

I'm seeing the following events in my logs that seem meaningful:

```
_tokenExpiring: ErrorTimeout from signinSilent: ErrorTimeout: IFrame timed out without a response
...
raise: Error: IFrame removed from DOM
```

**Comment by pamapa** [comment] 2022-04-07 06:17
@luke-atp Background: Your silent renew process does not complete, due to a connection error. As long as that renew process does not fail this library retries. For each authorization request a **temporary state** object is created to recognize that request when we receive a response from the authorization server. The solution, which @kherock proposed should fix this.

**Comment by luke-atp** [comment] 2022-04-07 12:56
@pamapa that makes sense. Does that mean I should call `clearStaleState` manually in my application? Something like this:

```ts
this._userManager.events.addSilentRenewError(err => {
  this._userManager.clearStaleState();
});
```

**Comment by pamapa** [comment] 2022-04-07 13:15
@luke-atp until we have fixed in the library, that can be a possible workaround. Please also notice `clearStaleState` uses `StaleStateAgeInSeconds` settings (Default is 60*15) to know which ones to clear. If you need to tweak that setting please let us know...

**Closed** 2022-05-23 07:19 UTC
Labels: enhancement
