### ISSUE TITLE
How to get signin URL from UserManager?

### ISSUE THREAD

**Issue by FloforPresident** [authts/oidc-client-ts#860] opened 2023-01-27 08:59 UTC
Because I want to use an in-App-Browser in a Capacitor App i need to retrieve the signin URL with all query parameters by myself and redirect to it, instead of using UserManager's signinRedirect() function which is redirecting to the system default browser.

How is it possible to get this URL from the User Manager?

I have seen createSigninRequest() from OidcClient Object, but i can't access it from the UserManager.

This is how i need to open the signin Page:
`Browser.open({ url: "Signin URL here" });`

Does anyone know a solution for this?

**Comment by Badisi** [comment] 2023-01-27 09:37
Duplicate of #537.

See my comment [here](https://github.com/authts/oidc-client-ts/issues/537#issuecomment-1406247758) for an answer 😉.

**Closed** 2023-01-27 14:24 UTC
Labels: duplicate
