### ISSUE TITLE
Navigators raising unnecessary errors when closed or disposed

### ISSUE THREAD

**Issue by Badisi** [authts/oidc-client-ts#326] opened 2022-01-13 20:53 UTC
Version: **v2.0.0-rc.4**

While playing with the latest version I noticed that some new errors were raised, but I think they should not.

---

#### Example 1 : IFrameWindow

Calling `userManager.signinSilent()` while being logged out.

The following, at [IFrameWindow.ts#L59](https://github.com/authts/oidc-client-ts/blob/63ea517907bc6ee1b6bb6ba789da75dc99f452d2/src/navigators/IFrameWindow.ts#L59), will be raised :
```ts
close(): void {
  ...
  this._abort.raise(new Error("IFrame removed from DOM"));
  ...
}
```

Removing the iframe is normal behavior in that case, so it should not raise an error.

```shell
[UserManager] startSilentRenew: begin
[SilentRenewService] start: begin
[UserManager] getUser: begin
[UserManager] _loadUser: begin
[WebStorageStateStore] get('user:http://localhost:8080/auth/realms/demo:demo'): begin
[InMemoryWebStorage] getItem('oidc.user:http://localhost:8080/auth/realms/demo:demo'): begin
[UserManager] signinSilent: begin
[UserManager] _loadUser: begin
[WebStorageStateStore] get('user:http://localhost:8080/auth/realms/demo:demo'): begin
[InMemoryWebStorage] getItem('oidc.user:http://localhost:8080/auth/realms/demo:demo'): begin
[UserManager] _loadUser: no user storageString
[UserManager] _loadUser: no user storageString
[UserManager] getUser: user not found in storage
[UserManager] _signinStart: begin
[OidcClient] createSigninRequest: begin
[MetadataService] _getMetadataProperty('authorization_endpoint'): begin
[MetadataService] getMetadata: begin
[MetadataService] getMetadata: getting metadata from http://localhost:8080/auth/realms/demo/.well-known/openid-configuration
[JsonService] getJson: begin
[JsonService] getJson: url: http://localhost:8080/auth/realms/demo/.well-known/openid-configuration
[JsonService] getJson: HTTP response received, status 200
[MetadataService] getMetadata: merging remote JSON with seed metadata
[MetadataService] _getMetadataProperty('authorization_endpoint'): resolved
[OidcClient] createSigninRequest: Received authorization endpoint http://localhost:8080/auth/realms/demo/protocol/openid-connect/auth
[SigninState] toStorageString: begin
[WebStorageStateStore] set('38ca48dfc1724961a2aecab05f210c65'): begin
[UserManager] _signinStart: got signin request
[IFrameWindow] navigate: Using timeout of: 10
[IFrameWindow] navigate: begin
[IFrameWindow] navigate: setting URL in window
[WDS] Live Reloading enabled.
[IFrameWindow] navigate: got response from window
[IFrameWindow] _dispose: begin
[Event('Window navigation aborted')] raise: Error: IFrame removed from DOM
    at IFrameWindow.close (vendor.js:79346)
    at vendor.js:79276
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (vendor.js:80388)
    at _next (vendor.js:80410)
    at ZoneDelegate.invoke (polyfills.js:381)
    at Zone.run (polyfills.js:143)
    at polyfills.js:1285
    at ZoneDelegate.invokeTask (polyfills.js:415)
    at Zone.runTask (polyfills.js:187)
[UserManager] _signinEnd: begin
[OidcClient] processSigninResponse: begin
[OidcClient] readSigninResponseState: begin
[WebStorageStateStore] remove('38ca48dfc1724961a2aecab05f210c65'): begin
[SigninState.fromStorageString]
[OidcClient] processSigninResponse: received state from storage; validating response
[ResponseValidator] validateSigninResponse: begin
[ResponseValidator] _processSigninState: begin
[ResponseValidator] _processSigninState: state validated
[ResponseValidator] _processSigninState: Response was error login_required
[OidcClient] clearStaleState: begin
[WebStorageStateStore] getAllKeys: begin
[UserManager] removeUser: begin
[UserManager] storeUser: begin
[UserManager] removing user
[WebStorageStateStore] remove('user:http://localhost:8080/auth/realms/demo:demo'): begin
[InMemoryWebStorage] getItem('oidc.user:http://localhost:8080/auth/realms/demo:demo'): begin
[InMemoryWebStorage] removeItem('oidc.user:http://localhost:8080/auth/realms/demo:demo'): begin
[State.clearStaleState] got keys (2) ['efa2be9d8cb34f89ae9f6860aa7845d6', '3d6a91d95d1343f885f7523174a5e95c']
[WebStorageStateStore] get('efa2be9d8cb34f89ae9f6860aa7845d6'): begin
[State.fromStorageString]
[State.clearStaleState] got item from key:  efa2be9d8cb34f89ae9f6860aa7845d6 1642102789
[State.clearStaleState] removed item for key:  efa2be9d8cb34f89ae9f6860aa7845d6
[WebStorageStateStore] remove('efa2be9d8cb34f89ae9f6860aa7845d6'): begin
[WebStorageStateStore] get('3d6a91d95d1343f885f7523174a5e95c'): begin
[State.fromStorageString]
[State.clearStaleState] got item from key:  3d6a91d95d1343f885f7523174a5e95c 1642102768
[State.clearStaleState] removed item for key:  3d6a91d95d1343f885f7523174a5e95c
[WebStorageStateStore] remove('3d6a91d95d1343f885f7523174a5e95c'): begin
[UserManager] removeUser: user removed from storage
[UserManagerEvents] unload: canceling existing access token timers
[Timer('Access token expiring')] cancel: begin
[Timer('Access token expired')] cancel: begin
[Event('User unloaded')] raise:
```

---

#### Example 2 : PopupWindow

Calling `userManager.signinPopup()` while being logged out and closing the popup manually right after it opens.

The following, at [PopupWindow.ts#L60](https://github.com/authts/oidc-client-ts/blob/63ea517907bc6ee1b6bb6ba789da75dc99f452d2/src/navigators/PopupWindow.ts#L60), will be raised :
```ts
public close(): void {
  ...
  this._abort.raise(new Error("Popup closed"));
  ...
}
```

We already have the error `Popup closed by user`, so the other one should not be necessary.

```shell
[UserManager] signinPopup: begin
[UserManager] _signinStart: begin
[OidcClient] createSigninRequest: begin
[MetadataService] _getMetadataProperty('authorization_endpoint'): begin
[MetadataService] getMetadata: begin
[MetadataService] getMetadata: using cached values
[MetadataService] _getMetadataProperty('authorization_endpoint'): resolved
[OidcClient] createSigninRequest: Received authorization endpoint http://localhost:8080/auth/realms/demo/protocol/openid-connect/auth
[SigninState] toStorageString: begin
[WebStorageStateStore] set('ee206ac354ee41f9935e3adb5b59128f'): begin
[UserManager] _signinStart: got signin request
[PopupWindow] navigate: begin
[PopupWindow] navigate: setting URL in window
[Event('Window navigation aborted')] raise: Error: Popup closed by user
    at vendor.js:79418
    at timer (polyfills.js:2570)
    at ZoneDelegate.invokeTask (polyfills.js:415)
    at Object.onInvokeTask (vendor.js:37141)
    at ZoneDelegate.invokeTask (polyfills.js:414)
    at Zone.runTask (polyfills.js:187)
    at invokeTask (polyfills.js:496)
    at ZoneTask.invoke (polyfills.js:485)
    at data.args.<computed> (polyfills.js:2550)
[PopupWindow] _dispose: begin
[UserManager] _signinStart: error after preparing navigator, closing navigator window
[Event('Window navigation aborted')] raise: Error: Popup closed
    at PopupWindow.close (vendor.js:79434)
    at vendor.js:80102
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (vendor.js:80388)
    at _throw (vendor.js:80414)
    at ZoneDelegate.invoke (polyfills.js:381)
    at Object.onInvoke (vendor.js:37154)
    at ZoneDelegate.invoke (polyfills.js:380)
    at Zone.run (polyfills.js:143)
    at polyfills.js:1285
```

---

#### Example 3 : PopupWindow

Calling `userManager.signinPopup()` while being logged out and proceed with login.

The following, at [PopupWindow.ts#L60](https://github.com/authts/oidc-client-ts/blob/63ea517907bc6ee1b6bb6ba789da75dc99f452d2/src/navigators/PopupWindow.ts#L60), will be raised :
```ts
public close(): void {
  ...
  this._abort.raise(new Error("Popup closed"));
  ...
}
```

Closing the popup is normal behavior in that case, so it should not raise an error.

```shell
[UserManager] signinPopup: begin
[UserManager] _signinStart: begin
[OidcClient] createSigninRequest: begin
[MetadataService] _getMetadataProperty('authorization_endpoint'): begin
[MetadataService] getMetadata: begin
[MetadataService] getMetadata: using cached values
[MetadataService] _getMetadataProperty('authorization_endpoint'): resolved
[OidcClient] createSigninRequest: Received authorization endpoint http://localhost:8080/auth/realms/demo/protocol/openid-connect/auth
[SigninState] toStorageString: begin
[WebStorageStateStore] set('c91be46b10674906afd3c5da19326ca9'): begin
[UserManager] _signinStart: got signin request
[PopupWindow] navigate: begin
[PopupWindow] navigate: setting URL in window
[PopupWindow] navigate: got response from window
[PopupWindow] _dispose: begin
[Event('Window navigation aborted')] raise: Error: Popup closed
    at PopupWindow.close (vendor.js:79434)
    at vendor.js:79276
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (vendor.js:80388)
    at _next (vendor.js:80410)
    at ZoneDelegate.invoke (polyfills.js:381)
    at Object.onInvoke (vendor.js:37154)
    at ZoneDelegate.invoke (polyfills.js:380)
    at Zone.run (polyfills.js:143)
    at polyfills.js:1285
[UserManager] _signinEnd: begin
[OidcClient] processSigninResponse: begin
[OidcClient] readSigninResponseState: begin
[WebStorageStateStore] remove('c91be46b10674906afd3c5da19326ca9'): begin
[SigninState.fromStorageString]
...
```

**Comment by kherock** [comment] 2022-01-13 22:30
I actually had a fix for this originally in the logger improvements that was just out scope for the PR - basically just needs to have a couple of lines moved around in the IFrameWindow and PopupWindow code.

**Comment by pamapa** [comment] 2022-01-14 07:38
> I actually had a fix for this originally in the logger improvements that was just out scope for the PR - basically just needs to have a couple of lines moved around in the IFrameWindow and PopupWindow code.

I guess those two changes:
- https://github.com/authts/oidc-client-ts/pull/291#discussion_r774449005
- https://github.com/authts/oidc-client-ts/pull/291#discussion_r774449331

**Comment by pamapa** [comment] 2022-01-14 13:14
@kherock please fix that soon.

**Comment by kherock** [comment] 2022-01-14 18:47
I tested those changes again but it looks like moving the popup window's abort event only prevents Example 2.

I'd say examples 1 & 3 are by design. Maybe with some careful refactoring someone could get rid of those events. However they're debug logs that aren't present with `Log.INFO`, and calling close() while there are potentially still active event listeners should indeed raise an error. I think it makes sense that debug logs should show error events even when nothing is subscribed to them.

Regardless the only time an error event *must* be raised here is when the promise created in `navigate()` is unresolved and the window is closed programmatically. This event is really important here because the rejection handler calls `_dispose()` in order to clean up after itself. What you see in the logs is what happens when the event is raised after someone else already called the `_dispose()` method.

**Closed** 2022-01-15 08:43 UTC
Labels: bug
